Eng 4882 introduce keycloak integration
entando-samples/agenda-bundle-templates pull request #16
Opened 2023-06-07 13:50 UTC by MEM2677

2023-06-07 14:07 UTC, avdev4j requested changes

2023-06-07 14:07 UTC, avdev4j commented on microservices/springboot-agenda/src/main/java/com/entando/springbootagenda/controller/ContactController.java
> +    @PreAuthorize("hasRole('admin')")
is the getAll require the admin roles?

2023-06-07 14:07 UTC, avdev4j commented on microservices/springboot-agenda/src/main/java/com/entando/springbootagenda/controller/ContactController.java
> +    @PreAuthorize("hasRole('admin')")
same, the read operations need to be admin to be performed?

2023-06-07 14:07 UTC, avdev4j commented on microservices/springboot-agenda/src/main/resources/application-dev.yaml
> +ALLOWED_API_ORIGIN: http://localhost:3000,http://localhost:3001
quick suggestion, if the property is owned by the app (seems to be the case) that could be cool to add a prefix like:
```
app:
  allowed-api-origin: http://localhost:3000,http://localhost:3001
```

We can also follow the convention names (lower case, kebab case)

2023-06-07 16:43 UTC, MEM2677 commented on microservices/springboot-agenda/src/main/java/com/entando/springbootagenda/config/RestClientConfiguration.java
> +    public RestTemplate getRestTemplate() {
I confirm it's no longer necessary (probably was requested by a dependency that is not used anymore)

2023-06-07 16:43 UTC, MEM2677 commented on microservices/springboot-agenda/pom.xml
> +        <springdoc-openapi-ui.version>1.6.14</springdoc-openapi-ui.version>
Totally missed it, good catch!

2023-06-07 16:43 UTC, MEM2677 commented on microservices/springboot-agenda/src/main/java/com/entando/springbootagenda/controller/ContactController.java
> +//    @PreAuthorize("hasAnyRole('admin', 'user')")
Needed for initial (user testing) now there's appropriate test... removed.

2023-06-07 16:44 UTC, MEM2677 commented on microservices/springboot-agenda/src/main/java/com/entando/springbootagenda/controller/ContactController.java
> +    @PreAuthorize("hasRole('admin')")
By ticket specificiation yes, but I created also a "user" role just in case. @firegloves what do you say?

2023-06-07 16:44 UTC, MEM2677 commented on microservices/springboot-agenda/src/main/java/com/entando/springbootagenda/controller/ContactController.java
> +    @PreAuthorize("hasRole('admin')")
Ditto! Will update accordingly

2023-06-07 16:44 UTC, MEM2677 commented on microservices/springboot-agenda/src/main/resources/application-dev.yaml
> +ALLOWED_API_ORIGIN: http://localhost:3000,http://localhost:3001
Done!

2023-06-07 20:20 UTC, avdev4j commented on microservices/springboot-agenda/src/main/java/com/entando/springbootagenda/controller/ContactController.java
> +    @PreAuthorize("hasRole('admin')")
my bad @MEM2677; if it is in ticket so let's go but because it seems only read operations, we can validate that with @firegloves

2023-06-08 07:04 UTC, firegloves commented on microservices/springboot-agenda/src/main/java/com/entando/springbootagenda/controller/ContactController.java
> +    @PreAuthorize("hasRole('admin')")
Thanks guys, I'm looking at the relative figma mockup where we don't have any login screen. Let's proceed in this way please: protect every endpoint, test them just to be sure that the keycloak integration is working and at the end we will remove the authorization to let the MFEs work without auth

2023-06-08 07:04 UTC, firegloves commented on microservices/springboot-agenda/src/main/java/com/entando/springbootagenda/controller/ContactController.java
> +    @PreAuthorize("hasRole('admin')")
Same here

2023-06-08 13:21 UTC, avdev4j approved these changes

2023-06-08 15:24 UTC, merged