ENG-4954 Add Agenda React MFE
entando-samples/agenda-bundle-templates pull request #20
Opened 2023-06-13 16:27 UTC by alepintus

2023-06-16 13:29 UTC, firegloves requested changes

2023-06-16 13:29 UTC, firegloves commented on microfrontends/react-widget-agenda/.gitignore
> +yarn-error.log*
Is this file included in the parent one? Does it contain the same thing?

2023-06-16 14:05 UTC, avdev4j commented on microfrontends/react-widget-agenda/.gitignore
> +yarn-error.log*
@firegloves I think there is a slight overlap, but I wonder which strategy is the best. Quick though, it's a good idea to split .gitignore files to each component.

2023-06-16 14:06 UTC, avdev4j commented on microfrontends/react-widget-agenda/src/App.js
> +        // NOTE: data-theme is for propagate the css variables theme through the shadow dom
@alepintus that might explain why we don't meet the issue here ;)

2023-06-16 14:08 UTC, avdev4j approved these changes

2023-06-19 12:49 UTC, firegloves approved these changes
LGTM

2023-06-22 09:49 UTC, merged