[ENG-5036] First version of the readme
entando-samples/agenda-bundle-templates pull request #28
Opened 2023-07-14 07:52 UTC by avdev4j

2023-07-19 16:03 UTC, firegloves requested changes

2023-07-19 17:08 UTC, jyunmitch commented on README.md
> +If you need any further assistance or have any questions, please refer to the project documentation or reach out to our [Community Slack](https://join.slack.com/t/entandocommunity/shared_invite/zt-g6
```suggestion
If you need further assistance or have any questions, please refer to the project documentation or reach out to our [Community Slack](https://join.slack.com/t/entandocommunity/shared_invite/zt-g609owdv-2K~YRh8zrI6lqlWo4aFWUw) for help.
```

2023-07-20 07:33 UTC, avdev4j commented on README.md
> +The microfrontends are delivered with a preconfigured API Claims to work both locally, and on the Entando platform.
@jyunmitch There is one API Claim per micro frontend.

2023-07-20 07:44 UTC, avdev4j commented on README.md
> +The purpose of this bundle is to provide users with a sample or template to kickstart their own application development.
we might prefer users to consider it as a template rather than a template. Makes sense

2023-07-20 12:08 UTC, avdev4j commented on README.md
> +Replace `<hub_url>` with the URL of the hub from where you want to initialize your bundle.
@jyunmitch This part should be replaced with the official Hub URL, for now we might add the dev one.

2023-07-20 12:11 UTC, avdev4j commented on README.md
> +Replace <mfe_name> with the name of the microfrontend you want to remove (e.g., vue-widget-agenda, angular-widget-agenda, react-widget-agenda).
@jyunmitch I will add a quick sentence to explain, but the bundle provides 3 MFEs that are basically doing the same thing. It's just 3 different technical implementations. That means the final will probably not keep all 3 of them but will use one and add others according to what he needs.

2023-07-20 12:22 UTC, avdev4j commented on README.md
> +Replace <mfe_name> with the name of the microfrontend you want to remove (e.g., vue-widget-agenda, angular-widget-agenda, react-widget-agenda).
Oh no sorry, This was an error of copy and past. I move that to the right section.

2023-07-20 12:25 UTC, avdev4j commented on README.md
> +- Then open the "Users" menu, search for your user (the user you are connected to the agenda-bundle application), and click on the "Role Mappings" tab
I finally used `the user to be granted to use the agenda-bundle components
the user to be granted to use the agenda-bundle components`

2023-07-20 15:53 UTC, jyunmitch commented on README.md
> +- Then open the "Users" menu, search for your user (the user you are connected to the agenda-bundle application), and click on the "Role Mappings" tab
the user to be granted access to the agenda-bundle components

2023-07-20 15:58 UTC, jyunmitch approved these changes

2023-07-26 13:09 UTC, firegloves approved these changes
LGTM

2023-07-26 14:03 UTC, firegloves commented on README.md
> +You can take inspiration from these workflows to automate your development.
@jyunmitch can you have a look at these lines please?

2023-07-28 07:51 UTC, merged

2023-07-28 13:57 UTC, jyunmitch commented on README.md
> +Because Entando follows the philosophy of composition, all 3 microfrontends use TailwindCSS and DaisyUI (also applying a custom theme) with the goal of pushing composition to the most advanced levels
```suggestion
Because Entando follows composable methodologies, all 3 micro frontends use TailwindCSS and DaisyUI (also applying a custom theme) with the goal of pushing composability to the most advanced levels, and allowing developers to focus on functionality instead of reinventing the wheel.
```

2023-07-28 14:15 UTC, jyunmitch commented
Sorry for the delay, the notification got buried in the emails